# Generated by Django 5.0.3 on 2024-03-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='pics')),
                ('Date_of_birth', models.DateField()),
                ('Age', models.IntegerField(blank=True, null=True, verbose_name='Age of the person')),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email address')),
                ('Class', models.CharField(max_length=100)),
                ('Blood_group', models.CharField(max_length=20)),
                ('Parent_Contact', models.PositiveBigIntegerField()),
                ('Address', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='pics')),
                ('Date_of_birth', models.DateField()),
                ('Age', models.IntegerField(blank=True, null=True, verbose_name='Age of the person')),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email address')),
                ('Contact', models.PositiveBigIntegerField()),
                ('Teaching_area', models.CharField(max_length=100)),
                ('Address', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
