# Generated by Django 5.0.3 on 2024-03-25 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Blood_group',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Class',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='Parent_Contact',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Date_of_birth',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Teaching_area',
        ),
    ]
