# Generated by Django 5.0.3 on 2024-03-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0002_remove_student_address_remove_student_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Blood_group',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Class',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='Parent_Contact',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Age of the person'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Contact',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='Teaching_area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
