# Generated by Django 5.0.3 on 2024-03-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0003_student_blood_group_student_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='student_image_admin/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='Blood_group',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
