# Generated by Django 5.0.3 on 2024-03-28 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_teacher_image_alter_student_blood_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='myproject/teacher_image_admin/'),
        ),
    ]
