# Generated by Django 5.0.3 on 2024-03-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0005_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_image_admin'),
        ),
    ]
