# Generated by Django 5.0.3 on 2024-03-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0006_alter_teacher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Image1',
            field=models.ImageField(blank=True, null=True, upload_to='student_image_admin/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='teacher_image_admin/'),
        ),
    ]
