# Generated by Django 5.0.3 on 2024-03-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0007_student_image1_alter_teacher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Image1',
            field=models.ImageField(blank=True, null=True, upload_to='student_image_admin'),
        ),
    ]
